title: "CÃ©sar Feniou"
description: "Quantum Research Scientist"
url: "https://cesarfeniou.github.io"

baseurl: ""

markdown: kramdown

# Keep it minimal: no plugins at start
plugins: []

# Optional: nicer permalinks later
permalink: pretty
