title: "CÃ©sar Feniou"
description: "Quantum Research Scientist"
url: "https://cesarfeniou.github.io"
baseurl: ""

baseurl: ""

markdown: kramdown

# Keep it minimal: no plugins at start
plugins: []

# Optional: nicer permalinks later
permalink: pretty

plugins:
  - jekyll-scholar

scholar:
  source: _bibliography
  bibliography: papers.bib
  style: apa
  sort_by: year
  order: descending
