title: "CÃ©sar Feniou"
description: "Quantum Research Scientist"
url: "https://cesarfeniou.github.io"
baseurl: ""

baseurl: ""

markdown: kramdown

permalink: pretty

plugins:
  - jekyll-scholar

scholar:
  source: _bibliography
  bibliography: papers.bib
  template: bib   
  style: apa
  sort_by: year
  order: descending
